# Customer Churn Exploration

## Objective
Load the customer churn dataset and understand its
structure before performing detailed analysis.

## Questions
- How many customers are in the dataset?
- What columns are available?
- Which column identifies churn?

In [1]:
from pathlib import Path
import pandas as pd

DATA_PATH = Path(
    "../data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv"
)

df = pd.read_csv(DATA_PATH)

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [2]:
df.shape

(7043, 21)

In [3]:
df.columns.tolist()

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn']

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [5]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [6]:
df["Churn"].value_counts(dropna=False)

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [7]:
df["Churn"].value_counts(
    normalize=True,
    dropna=False
) * 100

Churn
No     73.463013
Yes    26.536987
Name: proportion, dtype: float64

In [8]:
print("Duplicate rows:", df.duplicated().sum())

missing = df.isna().sum().sort_values(ascending=False)

print("Missing values per column:")
print(missing[missing > 0])

print("\nMissing percentage:")
print((df.isna().mean() * 100).round(2).sort_values(ascending=False))

Duplicate rows: 0
Missing values per column:
Series([], dtype: int64)

Missing percentage:
customerID          0.0
gender              0.0
SeniorCitizen       0.0
Partner             0.0
Dependents          0.0
tenure              0.0
PhoneService        0.0
MultipleLines       0.0
InternetService     0.0
OnlineSecurity      0.0
OnlineBackup        0.0
DeviceProtection    0.0
TechSupport         0.0
StreamingTV         0.0
StreamingMovies     0.0
Contract            0.0
PaperlessBilling    0.0
PaymentMethod       0.0
MonthlyCharges      0.0
TotalCharges        0.0
Churn               0.0
dtype: float64

In [9]:
print("Unique values per column:")
print(df.nunique().sort_values())

print("\nChurn distribution:")
print(df["Churn"].value_counts(dropna=False))

print("\nUnique customer IDs:")
print(df["customerID"].nunique())

Unique values per column:
gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
PhoneService           2
PaperlessBilling       2
Churn                  2
MultipleLines          3
TechSupport            3
StreamingTV            3
OnlineBackup           3
DeviceProtection       3
StreamingMovies        3
Contract               3
OnlineSecurity         3
InternetService        3
PaymentMethod          4
tenure                73
MonthlyCharges      1585
TotalCharges        6531
customerID          7043
dtype: int64

Churn distribution:
Churn
No     5174
Yes    1869
Name: count, dtype: int64

Unique customer IDs:
7043

In [10]:
if "TotalCharges" in df.columns:
    print(df["TotalCharges"].head(10))
    print(df["TotalCharges"].dtype)

0      29.85
1     1889.5
2     108.15
3    1840.75
4     151.65
5      820.5
6     1949.4
7      301.9
8    3046.05
9    3487.95
Name: TotalCharges, dtype: str
str

In [12]:
if "TotalCharges" in df.columns:
    df["TotalCharges"] = pd.to_numeric(
        df["TotalCharges"],
        errors="coerce"
    )

    print(
        "Missing TotalCharges after conversion:",
        df["TotalCharges"].isna().sum()
    )

    print(df["TotalCharges"].dtype)

Missing TotalCharges after conversion: 11
float64

issue             evidence                          decision                    reason 

duplicate rows    0.0                               0.0                         some repeated records may be legitimate

missing values    0.0                               0.0                         missingness can affect analysis

totalcharges      str                               0.0                         numeric analysis requires numeric data
data type 

customer IDs      7043/7043                         0.0                         IDs are expected to identify customers uniquely

Problem                                                      Rule for this project

Spaces around column names                                  Remove unnecessary leading and trailing spaces

TotalCharges stored as text                                 Convert to numeric values

Invalid numeric strings                                     Convert to missing values and investigate

Exact duplicate rows                                        Remove only after reviewing the audit

Missing Churn labels                                        Investigate; don't invent labels

Missing numerical values                                    Don't automatically replace them with zero

#day 3 cleaning process

In [3]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent

sys.path.insert(0, str(PROJECT_ROOT))

print("Project root:", PROJECT_ROOT)
print("Root exists:", PROJECT_ROOT.exists())
print("Source folder exists:", (PROJECT_ROOT / "src").exists())

Project root: c:\Users\Admin\OneDrive\Desktop\PYTHON PROJECT
Root exists: True
Source folder exists: True

In [4]:

from pathlib import Path
import pandas as pd

DATA_PATH = Path(
    "../data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv"
)

raw_df = pd.read_csv(DATA_PATH)

from src.data_processing import clean_customer_data

clean_df = clean_customer_data(raw_df)

print("Raw shape:", raw_df.shape)
print("Clean shape:", clean_df.shape)

print("\nData types:")
print(clean_df.dtypes)

print("\nMissing values:")
print(clean_df.isna().sum())

print("\nFirst five cleaned rows:")
display(clean_df.head())

Raw shape: (7043, 21)
Clean shape: (7043, 21)

Data types:
customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges        Float64
Churn                   str
dtype: object

Missing values:
customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

First five cleaned rows:

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:

processed_path = Path(
    "../data/processed/customers_clean.csv"
)

processed_path.parent.mkdir(
    parents=True,
    exist_ok=True
)

clean_df.to_csv(processed_path, index=False)

print("Cleaned dataset saved to:", processed_path)
print("File exists:", processed_path.exists())

Cleaned dataset saved to: ..\data\processed\customers_clean.csv
File exists: True

In [6]:

check_df = pd.read_csv(processed_path)

print("Saved file shape:", check_df.shape)
print("Original shape:", raw_df.shape)
print("Cleaned shape:", clean_df.shape)

print("\nColumn names preserved:")
print(raw_df.columns.tolist() == clean_df.columns.tolist())

if "customerID" in raw_df.columns:
    print(
        "Unique IDs before:",
        raw_df["customerID"].nunique()
    )
    print(
        "Unique IDs after:",
        clean_df["customerID"].nunique()
    )

if "Churn" in raw_df.columns:
    print("\nChurn values before:")
    print(raw_df["Churn"].value_counts(dropna=False))

    print("\nChurn values after:")
    print(clean_df["Churn"].value_counts(dropna=False))

print("\nReloaded file shape matches:")
print(check_df.shape == clean_df.shape)

Saved file shape: (7043, 21)
Original shape: (7043, 21)
Cleaned shape: (7043, 21)

Column names preserved:
True
Unique IDs before: 7043
Unique IDs after: 7043

Churn values before:
Churn
No     5174
Yes    1869
Name: count, dtype: int64

Churn values after:
Churn
No     5174
Yes    1869
Name: count, dtype: int64

Reloaded file shape matches:
True

day 3 - cleaning decisions 

changes made 
1 creted a resuale clean_customer_churn() function 

2 removed leading and trailing whitespaces from column names 

3 converted totalcharges to numeric when the column was present 

4 investigated exact duplicate rows and removed them only when justified 

5 saved the processed dataset separately from original csv

validations

. original dateset shape:[insert actual result]
. ck=leaned dataset shape:[insert actual result]
. number of exact duplicate rows removed:[insert actual result]
. missing values after conversion:[insert actual result]
. customer IDs and churn lables checked:[describe actual result]

notes 
the original csv remains unchanged. the cleaning process can be rerun to regenate the processed dataset 
missing values will be handled according to documented rules rather than arbitary assumptions